trigger:
  branches:
    include:
      - backend-main

variables:
  GITHUB_USERNAME: 'EmsiJoseph'
  GITHUB_REPO: 'greshamie.recordings.backend'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none

- script: |
    set -euxo pipefail

    # 1. Clone the GitHub repository
    git clone https://$GITHUB_USERNAME:$GITHUB_PAT@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
    cd $GITHUB_REPO

    # 2. Configure Git identity
    git config user.email "Mcjoseph.Agbanlog@wizard-ai.com"
    git config user.name "Azure DevOps"

    # 3. Add Azure DevOps remote
    git remote add azure https://$(System.AccessToken)@wizardcloud.visualstudio.com/Gresham%20Recordings/_git/Gresham%20Recordings

    # 4. Fetch and checkout the Azure backend-main branch
    git fetch azure backend-main
    git checkout azure/backend-main

    # 5. Debug: List directories
    echo "Current directory structure:"
    ls -la

    # 6. Verify backend directory exists
    if [ -d "backend" ]; then
        echo "Backend directory found"
    else
        echo "Backend directory not found"
        exit 1
    fi

    # 7. Create and switch to a new branch
    git checkout -b temp-branch

    # 8. Perform the subtree split
    git subtree split --prefix=backend -b backend-split

    # 9. Create and switch to main branch
    git checkout -b main

    # 10. Merge the split branch
    git merge backend-split --allow-unrelated-histories -m "Update backend from Azure"

    # 11. Push to GitHub
    git push origin main --force

    # 12. Cleanup
    git branch -D backend-split
    git branch -D temp-branch
  env:
    GITHUB_PAT: $(GITHUB_PAT)