trigger:
  branches:
    include:
      - main

variables:
  GITHUB_USERNAME: 'EmsiJoseph'
  GITHUB_REPO: 'gresham.recordings'
  DEV_BRANCH: 'dev'
  PROD_BRANCH: 'prod'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git clone https://$GITHUB_USERNAME:$GITHUB_PAT@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git 
    
    cd $GITHUB_REPO

    # Configure Git identity
    git config --global user.email "Mcjoseph.Agbanlog@wizard-ai.com"
    git config --global user.name "Azure DevOps"

    git remote add azure https://$(System.AccessToken)@wizardcloud.visualstudio.com/Gresham%20Recordings/_git/Gresham%20Recordings
    git fetch azure main 

    # Push main to dev branch
    git checkout -B $(DEV_BRANCH) azure/main
    git push origin $(DEV_BRANCH) --force

    # Merge dev into prod
    git fetch origin $(PROD_BRANCH)
    if git show-ref --verify --quiet refs/remotes/origin/$(PROD_BRANCH); then
      git checkout $(PROD_BRANCH)
      git merge --no-ff origin/$(DEV_BRANCH) -m "Merge dev into prod"
    else
      git checkout -b $(PROD_BRANCH)
      git merge --no-ff origin/$(DEV_BRANCH) -m "Initial merge of dev into prod"
    fi
    git push origin $(PROD_BRANCH)
  displayName: 'Sync branches'
  env:
    GITHUB_PAT: $(GITHUB_PAT)