trigger:
  branches:
    include:
      - backend-main

variables:
  - name: GITHUB_USERNAME
    value: EmsiJoseph
  - name: GITHUB_REPO
    value: greshamie.recordings.backend

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- script: |
    git remote remove github || true
    git remote add github https://$GITHUB_USERNAME:$GITHUB_PAT@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
    git config --global user.email "Mcjoseph.Agbanlog@wizard-ai.com"
    git config --global user.name "Azure DevOps"

    # Fetch the latest changes from the remote repository
    git fetch github main

    # Switch to the main branch and make sure it's up to date
    git checkout main
    git pull github main

    # Add only the backend directory and commit changes
    git add backend/
    git diff --cached --quiet || git commit -m "Update backend files from Azure DevOps"

    # Push only the updates (no --force)
    git push github main
  env:
    GITHUB_PAT: $(GITHUB_PAT)
