trigger:
  branches:
    include:
      - backend-main

variables:
  GITHUB_USERNAME: 'EmsiJoseph'
  GITHUB_REPO: 'greshamie.recordings.backend'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none

- script: |
    # Exit immediately if any command fails, print each command, and treat unset variables as errors.
    set -euxo pipefail

    # 1. Clone the GitHub repository using your PAT for authentication.
    git clone https://$GITHUB_USERNAME:$GITHUB_PAT@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
    cd $GITHUB_REPO

    # 2. Configure Git identity for commit attribution.
    git config user.email "Mcjoseph.Agbanlog@wizard-ai.com"
    git config user.name "Azure DevOps"

    # 3. Add the Azure DevOps repository as a remote named "azure".
    #    Ensure "Allow scripts to access the OAuth token" is enabled.
    git remote add azure https://$(System.AccessToken)@wizardcloud.visualstudio.com/Gresham%20Recordings/_git/Gresham%20Recordings

    # 4. Fetch the backend-main branch from the azure remote.
    git fetch azure backend-main

    # 5. (Optional) List directories in the remote branch for debugging.
    echo "Directories in azure/backend-main:"
    git ls-tree -d azure/backend-main

    # 6. Get the last commit hash that affected the 'backend' folder.
    LAST_BACKEND_COMMIT=$(git log -n 1 --pretty=format:%H azure/backend-main -- backend)
    echo "Last commit hash affecting the backend folder: $LAST_BACKEND_COMMIT"

    # 7. Create a temporary branch (backend-split) that contains only the contents of the 'backend' folder
    #    as of the last commit that touched it.
    git subtree split --prefix=backend -b backend-split $LAST_BACKEND_COMMIT

    # 8. Merge the subtree branch into the current branch (main) with a squash commit.
    git merge --squash backend-split -m "Update backend from Azure"

    # 9. Remove the temporary branch.
    git branch -D backend-split

    # 10. Push the changes to GitHub.
    git push origin main
  env:
    GITHUB_PAT: $(GITHUB_PAT)
