trigger:
  branches:
    include:
      - backend-main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    # Exit immediately on any error, print each command, and treat unset variables as errors.
    set -euxo pipefail

    echo "Repository URL: $(Build.Repository.Uri)"

    # 1. Add the current repository as a remote called 'azure'.
    #    This simulates adding your Azure DevOps repo as a remote.
    git remote add azure $(Build.Repository.Uri)
    
    # 2. Fetch the backend-main branch from the 'azure' remote.
    git fetch azure backend-main

    # 3. List the directories at the root of the backend-main branch.
    echo "Listing directories in azure/backend-main:"
    git ls-tree -d azure/backend-main
  displayName: 'Test: List Directories from azure/backend-main'
