version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - gresham-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --deploy-hook \"nginx -s reload\"; done'"

  frontend:
    image: mcagbanlog/gresham-recordings-frontend:latest  # Use the prebuilt Docker image
    environment:
      - NEXT_PUBLIC_GRESHAM_BACKEND=${NEXT_PUBLIC_GRESHAM_BACKEND}
      - NEXT_PUBLIC_GRESHAM_AUTH=${NEXT_PUBLIC_GRESHAM_AUTH}
    networks:
      - gresham-network

  backend:
    image: mcagbanlog/gresham-recordings-backend:latest  # Use the prebuilt Docker image
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ConnectionStrings__LocalDefaultConnection=${DB_CONNECTION_STRING}
      - ConnectionStrings__AzureBlobStorage=${AZURE_BLOB_CONNECTION}
      - AllowedOrigins=${ALLOWED_ORIGINS}
      - AdminCredentials__Password=${ADMIN_PASSWORD}
      - AdminCredentials__UserName=${ADMIN_USERNAME}
      - AuthSettings__ClientId=${AUTH_CLIENT_ID}
      - AuthSettings__ClientSecret=${AUTH_CLIENT_SECRET}
      - AuthSettings__Scope=${AUTH_SCOPE}
      - ClarifyGoAPI__ApiBaseUri=${CLARIFYGO_API_BASE_URI}
      - ClarifyGoAPI__IdentityServerUri=${CLARIFYGO_IDENTITY_URI}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryHours=${JWT_EXPIRY_HOURS}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Key=${JWT_KEY}
      - ASPNETCORE_URLS=http://+:80
      - ReverseProxy__Clusters__nextjsCluster__Destinations__nextjs__Address=http://frontend:3000
    networks:
      - gresham-network

volumes:
  certs:
  certs-data:

networks:
  gresham-network:
    driver: bridge
